#MinGW Makefile
simplest_ffmpeg_player:
	g++ simplest_ffmpeg_player.cpp -g -o simplest_ffmpeg_player.exe -I /usr/local/include -L /usr/local/lib -lSDL2main -lSDL2 -lavformat -lavcodec -lavutil -lswscale -lm -lz -pthread -lswresample
clean:
	rm simplest_ffmpeg_player
